---
name: "Release"

on:
  push:
    tags:
      - "*"

env:
  # NOTE: the IMAGE_PATH variable needs to be set as an environment variable on each
  #       repository for this variable to be properly set, otherwise it will be blank.
  IMAGE: "${{ vars.ORG_IMAGE_REGISTRY_HOSTNAME }}/${{ vars.IMAGE_PATH }}"

jobs:
  Release:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: "Set up Go"
        uses: "actions/setup-go@v5"
        with:
          go-version: "1.23"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"
        
      - name: "Login to Image Registry"
        uses: "docker/login-action@v3"
        with:
          registry: "quay.io"
          username: "${{ secrets.QUAY_USER }}"
          password: "${{ secrets.QUAY_PASSWORD }}"
      
      - name: "Build and Push"
        uses: "docker/build-push-action@v5"
        with:
          context: "."
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: "quay.io/mobb/windows-overcommit-webhook:${{ github.ref_name }},quay.io/mobb/windows-overcommit-webhook:latest"
